version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vue/docker/vue/package/00"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/django/docker/django/requirements/01"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"