include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - package
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

package:
  image: docker:20
  stage: package
  services:
    - docker:20-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - cd django
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build --push --platform linux/amd64,linux/arm64/v8 -t $IMAGE_TAG .
  only:
    changes: 
      - django/*
