version: "2"

services:
  pdb:
    image: postgis/postgis:11-2.5-alpine
    hostname: pdb

  vue:
    image: smartuse/gemeindescan-webui-vue:0.3.10
    hostname: vue

  django:
    image: smartuse/gemeindescan-webui-django:3.1.12a
    hostname: django

  www:
    image: openresty/openresty:1.19.3.1-alpine-fat
    hostname: www
