version: "2"

services:
  pdb:
    image: postgis/postgis:12-2.5-alpine
    hostname: pdb

  vue:
    image: smartuse/gemeindescan-webui-vue:0.3.10
    hostname: vue

  django:
    image: registry.gitlab.com/cividi/dfour/dfour-hub:latest
    hostname: django
  
  celery_worker:
    image: registry.gitlab.com/cividi/dfour/dfour-hub:latest
    hostname: celery_worker
  
  celery_beat:
    image: registry.gitlab.com/cividi/dfour/dfour-hub:latest
    hostname: celery_beat

  flower:
    image: registry.gitlab.com/cividi/dfour/dfour-hub:latest
    hostname: flower

  www:
    image: openresty/openresty:1.19.3.1-alpine-fat
    hostname: www
