"""added user table∆

Revision ID: fa5335e8669c
Revises: 
Create Date: 2020-01-09 14:22:30.323827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5335e8669c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_users_email'), 'user_users', ['email'], unique=True)
    op.create_index(op.f('ix_user_users_full_name'), 'user_users', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_users_id'), 'user_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_users_id'), table_name='user_users')
    op.drop_index(op.f('ix_user_users_full_name'), table_name='user_users')
    op.drop_index(op.f('ix_user_users_email'), table_name='user_users')
    op.drop_table('user_users')
    # ### end Alembic commands ###
