# Generated by Django 3.1.4 on 2021-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='example_gallery_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
