# Generated by Django 3.1.14 on 2022-08-30 12:28

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import parler.fields
import parler.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siteconfiguration_example_gallery_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hero', models.BooleanField(default=False)),
                ('siteConfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteconfiguration')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentSectionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', markdownx.models.MarkdownxField(blank=True, verbose_name='Markdown')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='assets')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.contentsection')),
            ],
            options={
                'verbose_name': 'content section Translation',
                'db_table': 'main_contentsection_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
