from django.contrib.gis import admin
from django.contrib.postgres import fields
from django.utils.translation import gettext as _
from django_json_widget.widgets import JSONEditorWidget
from django.utils.html import mark_safe
from django.contrib import messages
from sortedm2m_filter_horizontal_widget.forms import SortedFilteredSelectMultiple
from gsmap.models import Municipality, Snapshot, Workspace
import requests


class MunicipalityAdmin(admin.OSMGeoAdmin):
    pass


class SnapshotAdmin(admin.OSMGeoAdmin):
    readonly_fields = ('id', 'created', 'modified', 'get_absolute_link',
                       'thumbnail_generated_image', 'screenshot_generated_image',
                       'thumbnail_manual_image', 'screenshot_manual_image')
    fieldsets = (
        (_('Meta'), {
            'fields': ('id', 'get_absolute_link', 'created', 'modified',
                       'is_showcase', 'archived', 'deleted', 'permission')
        }),
        (_('Main'), {
            'fields': ('title', 'topic', 'data'),
        }),
        (_('Screenshots autogenerated'), {
            'fields': ('thumbnail_generated', 'thumbnail_generated_image',
                       'screenshot_generated', 'screenshot_generated_image'),
        }),
        (_('Screenshots manual (overwrite)'), {
            'fields': ('thumbnail_manual', 'thumbnail_manual_image',
                       'screenshot_manual', 'screenshot_manual_image'),
        }),
        (_('Relations'), {
            'fields': ('municipality', 'predecessor', 'user'),
        }),
        # (_('geo'), {
        #     'fields':
        #     ('perimeter',),
        # }),
    )

    formfield_overrides = {
        fields.JSONField: {
            'widget': JSONEditorWidget
        },
    }

    list_display = ('id', 'title', 'municipality', 'permission', 'is_showcase',
                    'created', 'modified')
    list_filter = ('is_showcase', 'permission')
    search_fields = ['title', 'municipality__name', 'municipality__canton']

    def _image_display(self, url, width=None):
        return mark_safe(
            '<a href="{url}" target="_blank">'
            '<img src="{url}" width="{width}" height={height} />'
            '</a>'.format(url=url, width=width, height='auto'))

    def screenshot_generated_image(self, obj):
        return self._image_display(obj.screenshot_generated.url, width=300)

    def thumbnail_generated_image(self, obj):
        return self._image_display(obj.thumbnail_generated.url, width=200)

    def screenshot_manual_image(self, obj):
        return self._image_display(obj.screenshot_manual.url, width=300)

    def thumbnail_manual_image(self, obj):
        return self._image_display(obj.thumbnail_manual.url, width=200)


    def save_model(self, request, obj, form, change):
        try:
            obj.save()
        except (requests.exceptions.ReadTimeout, requests.exceptions.ConnectionError) as e:
            messages.error(request, "Couldn't create the screenshots, screenshot server problem.")


class WorkspaceAdmin(admin.OSMGeoAdmin):
    readonly_fields = ('id', 'created', 'modified', 'get_absolute_link')
    fieldsets = (
        (_('Meta'), {
            'fields': (
                'id', 'get_absolute_link',
                'created', 'modified'
            )
        }),
        (_('Main'), {
            'fields': ('title', 'description', 'snapshots'),
        }),
    )
    list_display = ('id', 'title', 'created', 'modified')
    search_fields = ['title']

    def formfield_for_manytomany(self, db_field, request=None, **kwargs):
        if db_field.name == 'snapshots':
            kwargs['widget'] = SortedFilteredSelectMultiple()
        return super().formfield_for_manytomany(db_field, request, **kwargs)


admin.site.register(Municipality, MunicipalityAdmin)
admin.site.register(Snapshot, SnapshotAdmin)
admin.site.register(Workspace, WorkspaceAdmin)
