#!/usr/bin/with-contenv sh

cd /opt/app

set -o errexit
set -o nounset

worker_ready() {
    celery -A main inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A main  \
    --broker="${CELERY_BROKER}" \
    flower