# Generated by Django 3.0.2 on 2020-01-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name'], 'verbose_name_plural': 'municipalities'},
        ),
    ]
