# Generated by Django 3.0.3 on 2020-02-13 23:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import gsmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0003_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='slug_hash',
            field=models.CharField(default=gsmap.models.create_slug_hash, max_length=8, unique=True),
        ),
    ]
