# Generated by Django 3.0.3 on 2020-02-19 08:16

from django.db import migrations, models
import gsmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0005_auto_20200218_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='slug_hash',
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
