# Generated by Django 3.0.3 on 2020-02-27 17:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0006_auto_20200219_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='perimeter',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
