# Generated by Django 3.0.3 on 2020-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0007_municipality_perimeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
