# Generated by Django 3.0.3 on 2020-03-06 15:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0010_snapshot_is_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='perimeter',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
