# Generated by Django 3.0.3 on 2020-04-05 08:50

from django.db import migrations, models
import gsmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0011_auto_20200306_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='permission',
            field=models.IntegerField(choices=[(gsmap.models.SnapshotPermission['PUBLIC'], 0), (gsmap.models.SnapshotPermission['NOT_LISTED'], 10)], default=gsmap.models.SnapshotPermission['PUBLIC']),
        ),
    ]
