# Generated by Django 3.0.3 on 2020-04-05 15:55

from django.db import migrations, models
import gsmap.models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0012_auto_20200405_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='permission',
            field=models.IntegerField(choices=[(0, 'PUBLIC'), (10, 'NOT_LISTED')], default=gsmap.models.SnapshotPermission['PUBLIC']),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.CharField(default=gsmap.models.create_slug_hash, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('snapshots', sortedm2m.fields.SortedManyToManyField(help_text=None, to='gsmap.Snapshot')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
