# Generated by Django 3.0.3 on 2020-04-05 16:22

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0013_auto_20200405_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotRaw',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gsmap.snapshot',),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='snapshots',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='gsmap.SnapshotRaw'),
        ),
    ]
