# Generated by Django 3.0.3 on 2020-04-06 18:03

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0014_auto_20200405_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnapshotRaw',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='snapshots',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='gsmap.Snapshot'),
        ),
    ]
