# Generated by Django 3.0.3 on 2020-04-27 12:32

from django.db import migrations, models
import gsmap.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0015_auto_20200406_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='snapshot-thumbnails'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='id',
            field=models.CharField(default=gsmap.models.create_slug_hash_6, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='screenshot',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='snapshot-screenshots'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.CharField(default=gsmap.models.create_slug_hash_5, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
