# Generated by Django 3.0.5 on 2020-04-29 21:18

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0016_auto_20200427_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='screenshot_generated',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='snapshot-screenshots'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='screenshot_manual',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='snapshot-screenshots'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='thumbnail_generated',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='snapshot-thumbnails'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='thumbnail_manual',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='snapshot-thumbnails'),
        ),
    ]
