# Generated by Django 3.0.3 on 2020-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0017_auto_20200429_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
