# Generated by Django 3.0.3 on 2020-11-03 16:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0018_auto_20200510_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='data-files'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
