# Generated by Django 3.0.3 on 2020-12-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0019_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='homepage_snippet',
            field=models.TextField(blank=True),
        ),
    ]
