# Generated by Django 3.0.3 on 2020-11-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0019_auto_20201103_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='data',
        ),
    ]
