# Generated by Django 3.0.3 on 2020-12-28 13:59

import os
import pathlib
from django.db import migrations
from django.conf import settings
from django.utils.text import slugify
from django.core.files import File
import json


def snapshot_copy_to_file(apps, schema_editor):
    Snapshot = apps.get_model('gsmap', 'Snapshot')
    # create dir if it doesn't exists
    pathlib.Path(f'{settings.MEDIA_ROOT}/data-files').mkdir(parents=True, exist_ok=True)
    os.chdir(settings.MEDIA_ROOT)
    for snapshot in Snapshot.objects.all():
        file_name = f'{slugify(snapshot.title)}_{snapshot.id}.json'
        data_file_name = os.path.join('/tmp', file_name)
        with open(data_file_name, 'w+') as json_file:
            json.dump(snapshot.data, json_file)
        with open(data_file_name, 'r') as json_file:
            snapshot.data_file = File(json_file, name=file_name)
            snapshot.data = {}
            snapshot.save()
            print(f'migrated {snapshot.id}')
        os.remove(data_file_name)

class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0019_auto_20201103_1648'),
    ]

    operations = [
        migrations.RunPython(snapshot_copy_to_file),
    ]
