# Generated by Django 3.1.4 on 2020-12-29 13:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0020_data-snapshot-to-file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_enabled', models.BooleanField(default=True)),
                ('homepage_snippet', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
