# Generated by Django 3.1.4 on 2020-12-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0021_siteconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
