# Generated by Django 3.1.12 on 2021-09-30 13:36

from django.db import migrations, models
import gsmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0022_delete_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='permission',
            field=models.IntegerField(choices=[(0, 'PUBLIC'), (10, 'NOT_LISTED')], default=gsmap.models.SnapshotPermission['NOT_LISTED']),
        ),
    ]
