# Generated by Django 3.1.12 on 2021-09-30 13:40

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0023_auto_20210930_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('hide_in_list', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('icon', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='category-icons')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('COM', 'Comment')], max_length=3)),
                ('data', models.JSONField(default=dict)),
                ('author_email', models.EmailField(max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gsmap.category')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsmap.workspace')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
