# Generated by Django 3.1.12 on 2021-10-01 13:26

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0023_auto_20210930_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('COM', 'Comment')], max_length=3)),
                ('data', models.JSONField(default=dict)),
                ('author_email', models.EmailField(max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('hide_in_list', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('icon', models.FileField(blank=True, null=True, upload_to='category-icons')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['my_order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='annotation-attachements')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsmap.annotation')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gsmap.category'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsmap.workspace'),
        ),
    ]
