# Generated by Django 3.1.12 on 2021-10-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0024_auto_20211001_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='annotations_open',
            field=models.BooleanField(default=False),
        ),
    ]
