# Generated by Django 3.1.13 on 2021-11-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0025_workspace_annotations_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='annotations_contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Contact email address'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='annotations_contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='Contact first & lastname'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='annotations_likes_enabled',
            field=models.BooleanField(default=True, help_text='Enable like buttons on workspace', verbose_name='Likes enabled'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='annotations_open',
            field=models.BooleanField(default=False, help_text='Enable annotations on workspace', verbose_name='Annotations enabled'),
        ),
    ]
