# Generated by Django 3.1.13 on 2021-11-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0025_workspace_annotations_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='annotations_contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='workspace',
            name='annotations_contact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='annotations_require_verification',
            field=models.BooleanField(default=True, help_text='Submitting an annotation requires validation via E-Mail.', verbose_name='E-Mail verification enabled'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='annotations_open',
            field=models.BooleanField(default=False, help_text='Enable annotations on workspace', verbose_name='Annotations enabled'),
        ),
    ]
