# Generated by Django 3.2.12 on 2022-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0026_auto_20211128_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='kind',
            field=models.CharField(choices=[('COM', 'Comment'), ('PLY', 'Polygon')], max_length=3),
        ),
    ]
