# Generated by Django 3.1.13 on 2022-02-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0027_alter_annotation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
    ]
