# Generated by Django 3.1.13 on 2022-02-21 22:43

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0028_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='categories',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='gsmap.Category'),
        ),
    ]
