# Generated by Django 3.1.13 on 2022-02-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0029_workspace_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
