# Generated by Django 3.1.13 on 2022-02-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0032_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='_name',
        ),
    ]
