# Generated by Django 3.1.13 on 2022-02-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0033_remove_untranslated_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['namespace'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='my_order',
        ),
        migrations.AddField(
            model_name='category',
            name='namespace',
            field=models.CharField(default='core/beteiligung', max_length=255),
        ),
    ]
