# Generated by Django 3.1.13 on 2022-02-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0034_auto_20220222_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='findme_enabled',
            field=models.BooleanField(default=False, help_text="Enable 'Find Me'", verbose_name='Find me enabled'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='mode',
            field=models.CharField(choices=[('OFF', 'Off'), ('MGT', 'Portfolio-/Flächenmanagement'), ('PAR', 'Beteiligung')], default='OFF', max_length=3),
        ),
        migrations.AddField(
            model_name='workspace',
            name='polygon_likes_enabled',
            field=models.BooleanField(default=False, help_text='Enable like buttons on polygon annotations', verbose_name='Polygon Likes enabled'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='polygon_open',
            field=models.BooleanField(default=False, help_text='Enable polygon annotation', verbose_name='Polygon annotations enabled'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='annotations_likes_enabled',
            field=models.BooleanField(default=True, help_text='Enable like buttons on marker annotations', verbose_name='Marker Likes enabled'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='annotations_open',
            field=models.BooleanField(default=False, help_text='Enable marker annotations', verbose_name='Marker Annotations enabled'),
        ),
    ]
