# Generated by Django 3.1.13 on 2022-02-23 13:23

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0036_auto_20220223_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='title',
            new_name='_title',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='description',
            new_name='_description',
        ),
        migrations.CreateModel(
            name='WorkspaceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gsmap.workspace')),
            ],
            options={
                'verbose_name': 'workspace Translation',
                'db_table': 'gsmap_workspace_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
