# Generated by Django 3.1.13 on 2022-02-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gsmap', '0039_auto_20220223_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
