# Generated by Django 3.1.13 on 2022-02-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0041_auto_20220223_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-created'], 'permissions': [('publish_annotation', 'Can publish annotations'), ('export_annotation', 'Can export annotations')]},
        ),
    ]
