# Generated by Django 3.1.14 on 2022-02-24 15:14

from django.db import migrations


def apply_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    default_groups = [
        Group(name="core/participation"),
        Group(name="core/areamanagement"),
        Group(name="default"),
    ]

    for g in default_groups:
        Group.objects.using(db_alias).get_or_create(name=g.name)

    permissions = [
        Permission.objects.get(codename='view_workspace'),
        Permission.objects.get(codename='view_annotation'),
        Permission.objects.get(codename='view_category'),
        Permission.objects.get(codename='view_usergroup'),
    ]

    default = Group.objects.using(db_alias).get(name="default")
    core_p_group = Group.objects.using(db_alias).get(name="core/participation")
    core_a_group = Group.objects.using(db_alias).get(name="core/areamanagement")

    default.permissions.set(permissions)
    core_p_group.permissions.set(permissions)
    core_a_group.permissions.set(permissions)
    
    # Add all users to new groups
    User = apps.get_model("gsuser", "User")
    users = User.objects.using(db_alias)
    default.user_set.add(*users)
    core_p_group.user_set.add(*users)
    core_a_group.user_set.add(*users)

    Category = apps.get_model("gsmap", "Category")
    Category.objects.using(db_alias).filter(group=None).update(group=default)

    Workspace = apps.get_model("gsmap", "Workspace")
    Workspace.objects.using(db_alias).filter(group=None).update(group=default)

    Usergroup = apps.get_model("gsmap", "Usergroup")
    Usergroup.objects.using(db_alias).filter(group=None).update(group=default)

def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["default", "core/participation", "core/areamanagement"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0042_auto_20220223_2331'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
