# Generated by Django 3.1.14 on 2022-03-14 11:57

from django.db import migrations, models
import gsmap.models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0043_default_groups_and_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialDatasette',
            fields=[
                ('id', models.CharField(default=gsmap.models.create_slug_hash_5, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('base_url', models.CharField(default='', help_text='Base URL of spatial Datasette including database name slug', max_length=255, verbose_name='Datasette URL')),
                ('queries', models.JSONField(default=list, help_text="List of canned queries objects to fetch from datasette in JSON format, e.g. [{name:'zonal_stats_bmz',summary_stat:'avg',title:'Baumassenziffer',description:'Durchschnittliche Baumassenziffer gemäss amtlicher Statistik.'}]")),
            ],
            options={
                'verbose_name': 'Spatial Datasette',
                'verbose_name_plural': 'Spatial Datasettes',
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='spatial_datasettes',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='gsmap.SpatialDatasette'),
        ),
    ]
