# Generated by Django 3.1.14 on 2022-03-14 15:51

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0044_auto_20220314_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='spatial_datasettes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='gsmap.SpatialDatasette'),
        ),
    ]
