# Generated by Django 3.1.14 on 2022-04-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0046_auto_20220406_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hide_in_legend',
            field=models.BooleanField(default=False, verbose_name='hide in legend'),
        ),
    ]
