# Generated by Django 3.1.14 on 2022-04-13 15:15

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gsmap', '0047_auto_20220406_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('hide_in_list', models.BooleanField(default=False, verbose_name='hide in list')),
                ('hide_in_legend', models.BooleanField(default=False, verbose_name='hide in legend')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-created'], 'permissions': [('publish_annotation', 'Can publish annotations'), ('export_annotation', 'Can export annotations')], 'verbose_name': 'annotation', 'verbose_name_plural': 'annotations'},
        ),
        migrations.AlterModelOptions(
            name='attachement',
            options={'ordering': ['my_order'], 'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name'], 'verbose_name': 'municipality', 'verbose_name_plural': 'municipalities'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['-created'], 'verbose_name': 'snapshot', 'verbose_name_plural': 'snapshots'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'usergroup', 'verbose_name_plural': 'usergroups'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created'], 'verbose_name': 'workspace', 'verbose_name_plural': 'workspaces'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='namespace',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='author_email',
            field=models.EmailField(max_length=254, verbose_name='author email'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='data',
            field=models.JSONField(default=dict, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='kind',
            field=models.CharField(choices=[('COM', 'Comment'), ('PLY', 'Polygon'), ('OBJ', 'Object')], max_length=3, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='category',
            name='hide_in_list',
            field=models.BooleanField(default=False, verbose_name='hide in list'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category-icons', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='usergrouptranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gsmap.state'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='states',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='gsmap.State'),
        ),
        migrations.CreateModel(
            name='StateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gsmap.state')),
            ],
            options={
                'verbose_name': 'State Translation',
                'db_table': 'gsmap_state_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
