# Generated by Django 3.1.14 on 2022-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0048_auto_20220413_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='object_likes_enabled',
            field=models.BooleanField(default=False, help_text='Enable like buttons on Object annotations', verbose_name='Object Likes enabled'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='object_open',
            field=models.BooleanField(default=False, help_text='Enable Object annotation', verbose_name='Object annotations enabled'),
        ),
    ]
