# Generated by Django 3.1.14 on 2022-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0049_auto_20220414_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='mode',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('MGT', 'Portfolio-/Flächenmanagement'), ('PAR', 'Beteiligung')], default='', max_length=3, null=True, verbose_name='Context'),
        ),
    ]
