# Generated by Django 3.1.14 on 2022-04-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0051_auto_20220414_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='objects_page_link',
            field=models.BooleanField(default=False, help_text='Show a Link to the Objects List/Grid Page in Sidebar', verbose_name='Show Objectslist Link'),
        ),
    ]
