# Generated by Django 3.1.14 on 2022-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0052_workspace_objects_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='decoration',
            field=models.CharField(blank=True, choices=[('', 'None'), ('GS', 'Grayscale')], default='', max_length=3, null=True, verbose_name='decoration'),
        ),
    ]
