# Generated by Django 3.1.14 on 2022-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0054_auto_20220501_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='decoration',
            field=models.CharField(blank=True, choices=[('', 'None'), ('GRAY', 'Grayscale')], default='', max_length=5, null=True, verbose_name='decoration'),
        ),
    ]
