# Generated by Django 3.1.14 on 2022-05-29 14:40

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0056_workspace_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='data',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
