# Generated by Django 3.1.14 on 2022-08-23 20:53

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gsmap', '0057_auto_20220529_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='author_email_shared',
            field=models.BooleanField(default=False, verbose_name='author email shared'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='data',
            field=django_jsonform.models.fields.JSONField(default=dict, verbose_name='data'),
        ),
    ]
